# Numpy Lib

In [1]:
import numpy as np

In [2]:
#List 


xs=[3,1,2]

print(xs,xs[0])

[3, 1, 2] 3


In [3]:
print(xs[-2],xs)

1 [3, 1, 2]


In [4]:
xs[1]="selin"

print(xs)

[3, 'selin', 2]


In [5]:
xs.append('bar')
print(xs)

[3, 'selin', 2, 'bar']


In [6]:
a=(int(input("enter values : ")))
b=(int(input("enter values : ")))
c=a+b
print("sum :",c)

enter values : 86
enter values : 99
sum : 185


In [7]:
a=(int(input("enter values : ")))
if(a>=50):
    print(a)
else:
    print("invalid no")
    

enter values : 40
invalid no


In [8]:
#While

n=3
i=1
while(i<=n):
    print("Easy")
    i=i+1
    
    

Easy
Easy
Easy


In [9]:
# Slicing

In [10]:
#nm=[0,1,2,4,5,6]

nms=list(range(50,90,2))

print(nms)



[50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88]


In [11]:
print(nms[2:4])
print(nms[3:])
print(nms[:5])

[54, 56]
[56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88]
[50, 52, 54, 56, 58]


In [12]:
print(nms[:])

[50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88]


In [13]:
a=np.array([1,2,3,7,8,9,88])
b=np.array([1,2,3,7,8,9,88])
print(type(a))
a
print(a)
print(b)
b

<class 'numpy.ndarray'>
[ 1  2  3  7  8  9 88]
[ 1  2  3  7  8  9 88]


array([ 1,  2,  3,  7,  8,  9, 88])

In [14]:
a.shape

(7,)

In [15]:
print(a.shape)

(7,)


In [16]:
a

array([ 1,  2,  3,  7,  8,  9, 88])

In [17]:
print(a[0],a[1],a[2],a[3])
a[3]=5
a[3]=5
print(a)

1 2 3 7
[ 1  2  3  5  8  9 88]


In [18]:
b=np.array([[1,2,3,9],[4,5,6,9],[4,5,6,9],[1,2,3,9],[4,5,6,9],[4,5,6,9]])
print(b.shape)
b

(6, 4)


array([[1, 2, 3, 9],
       [4, 5, 6, 9],
       [4, 5, 6, 9],
       [1, 2, 3, 9],
       [4, 5, 6, 9],
       [4, 5, 6, 9]])

In [19]:
#print(b[0,0],b[0,1],b[1,0])
print(b[5,3])

b

9


array([[1, 2, 3, 9],
       [4, 5, 6, 9],
       [4, 5, 6, 9],
       [1, 2, 3, 9],
       [4, 5, 6, 9],
       [4, 5, 6, 9]])

In [20]:
a=np.zeros((50,25))
print(a)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [21]:
a=np.ones((6,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
c=np.full((5,8),8)
print(c)

[[8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]]


In [23]:
e=np.random.random((5,4))

print(e)

[[0.91536256 0.6686684  0.25620306 0.11093057]
 [0.5616475  0.56887862 0.7612209  0.13981991]
 [0.65743164 0.13644309 0.92975955 0.12547352]
 [0.09759426 0.55964541 0.39995845 0.52348753]
 [0.27192444 0.46203236 0.56605483 0.810041  ]]


In [24]:

array = np.random.randn(5) 
print(array);

[-0.48287178  1.61800928  0.51936046  0.36905909  2.05326694]


In [25]:
a=np.array([[1,2,4,5,6],[4,5,6,7,7],[6,7,8,9,4],[1,2,4,5,5],[4,5,6,7,3],[6,7,8,9,6]])
print(a)

[[1 2 4 5 6]
 [4 5 6 7 7]
 [6 7 8 9 4]
 [1 2 4 5 5]
 [4 5 6 7 3]
 [6 7 8 9 6]]


In [26]:
b=a[:3,1:3]
print(b)


#b[0,4]

[[2 4]
 [5 6]
 [7 8]]


In [27]:
b=a[4:6,2:5]
print(b)

[[6 7 3]
 [8 9 6]]


In [28]:
a.shape

(6, 5)

In [29]:
b=a[1:4,2:4]

print(b)

[[6 7]
 [8 9]
 [4 5]]


In [30]:
b=a[2:5,1:4]
print(b)

[[7 8 9]
 [2 4 5]
 [5 6 7]]


In [31]:
a=np.arange(10,90,6)
print(a)

[10 16 22 28 34 40 46 52 58 64 70 76 82 88]


In [32]:
b=a[5]
print(b)

40


In [33]:
b=a[-5]
print(b)

64


In [34]:
a=np.array([[1,2,3,4],[2,3,4,5],[2,3,5,6]])

print(a)

[[1 2 3 4]
 [2 3 4 5]
 [2 3 5 6]]


In [35]:
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [2, 3, 5, 6]])

In [36]:
print(a[...,2])

[3 4 5]


In [37]:
print(a[1:2,...])

[[2 3 4 5]]


In [38]:
print(a[1:3,...])

[[2 3 4 5]
 [2 3 5 6]]


In [39]:
a=np.array([1,2,3,4,5])
b=np.array([2,4,5,6,7])

c=a*b

print(c)

[ 2  8 15 24 35]


In [40]:
a=np.array([1,2,3,4,5])
b=np.array([2,4,5,6,7])

c=b-a

print(c)

[1 2 2 2 2]


In [41]:
a=np.array([[1,2],[3,4],[5,6]])

print(a)
bd=(a>2)

print(bd)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [42]:
print(a[a>2])

[3 4 5 6]


In [43]:
x=np.array([1,2])

print(x.dtype)

int32


In [44]:
x=np.array([1,2],dtype=np.float64)

print(x.dtype)

float64


In [45]:
#Thank you